version: 2
jobs:
  objc-01:
    working_directory: ~/auth0-ios-objc-sample/01-Login
    macos:
      xcode: "10.0.0"
    environment:
        LC_ALL: en_US.UTF-8
        LANG: en_US.UTF-8
    steps:
      - checkout
      
      - run: 
          name: Install Homebrew dependencies
          command: brew upgrade yarn
      
      - run:
          name: Install node dependencies
          command: yarn install

      - run:
          name: Build and run tests
          command: |
            xcodebuild -workspace CLI.xcworkspace -scheme CLI -destination generic/platform=iOS build
            xcodebuild -workspace CLI.xcworkspace -scheme CLI -sdk iphoneos -configuration AppStoreDistribution archive -archivePath $PWD/build/CLI.xcarchive
            xcodebuild -exportArchive -archivePath $PWD/build/CLI.xcarchive -exportOptionsPlist exportOptions.plist -exportPath $PWD/build

      - store_test_results:
          path: output/scan

      - store_artifacts:
          path: output

workflows:
  version: 2
  build:
    jobs:
      -  objc-01